version: '3.8'

services:
  db:
    image: postgres:15
    container_name: quotes-postgres
    environment:
      POSTGRES_DB: quotesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
